DROP DATABASE IF EXISTS QuanLyDiem;
CREATE DATABASE IF NOT EXISTS QuanLyDiem;
USE QuanLyDiem;

DROP TABLE IF EXISTS 	Student;
CREATE TABLE IF NOT EXISTS 	Student (
RN 			TINYINT AUTO_INCREMENT PRIMARY KEY,
Name 		VARCHAR(30) NOT NULL,
Age 		TINYINT NOT NULL,
Gender 		ENUM('Male','Female') NOT NULL
);
INSERT INTO Student ( Name, Age, Gender)
VALUES 
( 'NGUYEN VIET ANH', 20, 'Male'),
( 'NGUYEN TAT THANH', 21, 'Male'),
( 'CAO THU THAO', 20, 'Female');

DROP TABLE IF EXISTS 	`Subject`;
CREATE TABLE IF NOT EXISTS 	`Subject` (
sID 		TINYINT AUTO_INCREMENT PRIMARY KEY,
sName 		VARCHAR(30) NOT NULL
);
INSERT INTO `Subject` ( sName)
VALUES 
( 'GIAI TICH 1'),
( 'GIAI TICH 2'),
( 'DAI SO');

DROP TABLE IF EXISTS 	StudentSubject;
CREATE TABLE IF NOT EXISTS 	StudentSubject (
RN 			TINYINT,
sID 		TINYINT,
Mark 		CHAR(3) NULL,
`Date` 		DATE,
FOREIGN KEY (RN)
        REFERENCES Student (RN),
FOREIGN KEY (sID)
        REFERENCES `Subject` (sID)
);
INSERT INTO StudentSubject (RN, sID, Mark, `Date`)
VALUES 
(1, 1, '9', '2020-05-05'),
(2, 3, NULL, '2020-04-05'),
(3, 2, '8', '2020-03-05');

SELECT sName
FROM `Subject`
WHERE sID IN (SELECT sID FROM StudentSubject WHERE Mark IS NULL);

SELECT sName
FROM `Subject` s
WHERE s.sID IN (SELECT ss.sID FROM StudentSubject ss WHERE ss.Mark >= 2);

DROP VIEW IF EXISTS StudentInfo;
CREATE VIEW StudentInfo AS
SELECT s.RN,sb.sID, s.`Name`, s.Age, s.Gender, sb.sName, ss.Mark, ss.`Date`
FROM Student s
JOIN StudentSubject ss ON s.RN = ss.RN
JOIN `Subject` sb ON ss.sID = sb.sID;
SELECT * FROM StudentInfo;


DROP PROCEDURE IF EXISTS XoaThongTin;
DELIMITER $$
CREATE PROCEDURE XoaThongTin(IN StudentName VARCHAR(30))
BEGIN
DROP TEMPORARY TABLE IF EXISTS REMOVE_STUDENT;
CREATE TEMPORARY TABLE REMOVE_STUDENT 
(
RN 			TINYINT,
Name 		VARCHAR(30),
Age 		TINYINT,
Gender 		ENUM('Male','Female')
);
INSERT INTO REMOVE_STUDENT (RN,Name,Age,Gender)
SELECT * FROM Student WHERE Name = StudentName;

DROP TEMPORARY TABLE IF EXISTS REMOVE_STUDENTSUBJECT;
CREATE TEMPORARY TABLE REMOVE_STUDENTSUBJECT
(
RN 			TINYINT,
sID 		TINYINT,
Mark 		CHAR(3),
`Date` 		DATE
);
INSERT INTO REMOVE_STUDENTSUBJECT (RN,sID,Mark,Date)
SELECT * FROM StudentSubject WHERE RN = (SELECT RN FROM REMOVE_STUDENT);

DROP TEMPORARY TABLE IF EXISTS REMOVE_SUBJECT;
CREATE TEMPORARY TABLE REMOVE_SUBJECT
(
sID 		TINYINT,
sName 		VARCHAR(30)
);
INSERT INTO REMOVE_SUBJECT(sID, sName)
SELECT * FROM `Subject` WHERE sID = (SELECT sID FROM REMOVE_STUDENTSUBJECT);

DELETE FROM StudentSubject WHERE RN = (SELECT RN FROM REMOVE_STUDENTSUBJECT );
DELETE FROM Student WHERE RN = (SELECT RN FROM REMOVE_STUDENT );
DELETE FROM `Subject` WHERE sID = (SELECT sID FROM REMOVE_SUBJECT );
END $$
DELIMITER ;

SELECT * FROM Student;
SELECT * FROM `Subject`;
SELECT * FROM StudentSubject;



