-- BT1
DROP DATABASE IF EXISTS FRESHER_MANAGEMENT;
CREATE DATABASE IF NOT EXISTS FRESHER_MANAGEMENT;
USE FRESHER_MANAGEMENT;

DROP TABLE IF EXISTS TRAINEE;
CREATE TABLE TRAINEE (
	TraineeID 			SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Full_Name 			NVARCHAR(30) NOT NULL,
    Birth_Date 			DATE NOT NULL,
    Gender 				ENUM('MALE','FEMALE') NOT NULL,
    ET_IQ  				TINYINT NOT NULL,
    ET_Gmath	    	TINYINT NOT NULL,
    ET_English  		TINYINT NOT NULL,
    Training_Class 		CHAR(10) NOT NULL,
    Evaluation_Notes    NVARCHAR(255) NULL
);
ALTER TABLE TRAINEE
ADD COLUMN VTI_Account VARCHAR(30) NOT NULL UNIQUE;

-- BT2
ID   			MEDIUMINT AUTO_INCREMENT
Name 			VARCHAR(30)
Code 			CHAR(5)
ModifiedDate 	DATETIME

-- BT3 
ID   			MEDIUMINT AUTO_INCREMENT
Name 			VARCHAR(30)
BirthDate 		DATE
Gender 			ENUM('0-male','1-female') NULL
IsDeleteFlag 	ENUM('0-danghoatdong','1-daxoa')


