DROP DATABASE IF EXISTS FRESHER;
CREATE DATABASE IF NOT EXISTS FRESHER;
USE FRESHER;

DROP TABLE IF EXISTS TRAINEE;
CREATE TABLE IF NOT EXISTS TRAINEE 
(
    TRAINEE_ID 			TINYINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME 			VARCHAR(30),
    BIRTH_DATE 			DATE,
    GENDER 				ENUM('MALE', 'FEMALE'),
    ET_IQ 				TINYINT,
    ET_GMATH 			TINYINT,
    ET_ENGLISH 			TINYINT,
    TRAINING_CLASS 		CHAR(10),
    EVALUATION_NOTES 	VARCHAR(255)
);
ALTER TABLE TRAINEE
ADD COLUMN VTI_ACCOUNT VARCHAR(30) UNIQUE;

INSERT INTO TRAINEE( FULL_NAME, BIRTH_DATE, GENDER, ET_IQ, ET_GMATH, ET_ENGLISH, TRAINING_CLASS, EVALUATION_NOTES, VTI_ACCOUNT )
VALUES 
(	'NGUYEN VIET ANH', 		'1999-09-10', 'MALE',  9,  9, 15, 'CNTT_A',  'TOT', 'ANH@VTI.COM.VN'		),
(	'BUI VAN TIEN', 		'1999-01-20', 'MALE', 10,  8, 16, 'CNTT_A',  'TOT', 'TIEN@VTI.COM.VN'		),
(	'LE VAN THANH', 		'1999-02-12', 'MALE',  8,  8,  8, 'CNTT_A',  'TOT', 'THANH@VTI.COM.VN'		),
(	'NGUYEN TAT THANH',		'1999-03-03', 'MALE', 10, 10, 19, 'CNTT_A',  'TOT', 'TTHANH@VTI.COM.VN'		),
(	'NGUYEN ANH TUAN', 		'1999-04-15', 'MALE',  7,  8,  6, 'CNTT_A',  'TOT', 'TUAN@VTI.COM.VN'		),
(	'NGUYEN MANH CUONG',	'1999-05-06', 'MALE', 10, 10, 20, 'CNTT_B',  'TOT', 'CUONG@VTI.COM.VN'		),
(	'PHAM MANH CUONG', 		'1999-06-08', 'MALE',  9,  9,  7, 'CNTT_B',  'TOT', 'PCUONG@VTI.COM.VN'		),
(	'NGUYEN HOANG THINH', 	'1999-09-29', 'MALE',  9, 10, 13, 'CNTT_B',  'TOT', 'THINH@VTI.COM.VN'		),
(	'NGUYEN VAN HOANG', 	'1999-10-09', 'MALE',  7,  7, 10, 'CNTT_B',  'TOT', 'HOANG@VTI.COM.VN'		),
(	'PHAM TIEN DAT', 		'1999-12-11', 'MALE', 10, 10, 19, 'CNTT_B',  'TOT', 'DAT@VTI.COM.VN'		);

SELECT * FROM TRAINEE;



